export interface GlossaryTerm {
  id: string;
  term: string; // Chinese name
  termEn: string; // English name
  definition: string; // One-sentence definition in Chinese
  example: string; // Simple example in Chinese
  category: "基础概念" | "技术术语" | "应用概念" | "商业/生态";
}

export const glossaryTerms: GlossaryTerm[] = [
  // ===== 基础概念 =====
  {
    id: "llm",
    term: "大语言模型",
    termEn: "LLM (Large Language Model)",
    definition: "在海量文本数据上训练的超大规模神经网络，能够理解和生成自然语言。",
    example: "ChatGPT、Claude、Gemini 都是大语言模型的产品化应用。",
    category: "基础概念",
  },
  {
    id: "transformer",
    term: "Transformer 架构",
    termEn: "Transformer",
    definition: "2017 年提出的神经网络架构，通过自注意力机制处理序列数据，是现代 LLM 的基础。",
    example: "GPT 的 T 就是 Transformer，整个架构让模型能同时关注输入中所有位置的信息。",
    category: "基础概念",
  },
  {
    id: "token",
    term: "词元",
    termEn: "Token",
    definition: "模型处理文本的最小单位，可以是一个字、一个词或一个子词片段。",
    example: "'Hello world' 被分成 ['Hello', ' world'] 两个 token；中文的'你好'可能是一个或两个 token。",
    category: "基础概念",
  },
  {
    id: "embedding",
    term: "嵌入向量",
    termEn: "Embedding",
    definition: "将文字、图片等信息转换为高维数字向量的技术，使计算机能理解语义相似性。",
    example: "'国王'和'女王'的向量在空间中距离很近，而'国王'和'苹果'距离较远。",
    category: "基础概念",
  },
  {
    id: "fine-tuning",
    term: "微调",
    termEn: "Fine-tuning",
    definition: "在预训练模型基础上，用特定领域或任务的数据继续训练，使模型适应特定需求。",
    example: "用医疗问答数据微调 LLM，让它在回答医学问题时更准确专业。",
    category: "基础概念",
  },
  {
    id: "neural-network",
    term: "神经网络",
    termEn: "Neural Network",
    definition: "模仿人脑神经元连接方式构建的计算模型，由多层节点组成，能学习复杂模式。",
    example: "神经网络通过不断调整连接权重来学习，就像大脑通过反复练习形成条件反射。",
    category: "基础概念",
  },
  {
    id: "deep-learning",
    term: "深度学习",
    termEn: "Deep Learning",
    definition: "使用多层(深层)神经网络的机器学习方法，能自动从数据中学习层次化特征表示。",
    example: "图像识别中，浅层学习边缘、中层学习纹理、深层学习物体形状，层层递进。",
    category: "基础概念",
  },
  {
    id: "pre-training",
    term: "预训练",
    termEn: "Pre-training",
    definition: "在大规模无标注数据上进行初始训练的阶段，让模型学习语言的通用知识和规律。",
    example: "GPT-4 的预训练需要数万张 GPU 运行数月，消耗数万亿 token 的文本数据。",
    category: "基础概念",
  },
  {
    id: "inference",
    term: "推理",
    termEn: "Inference",
    definition: "模型训练完成后，用它处理新输入并生成输出的过程。",
    example: "你向 ChatGPT 提问时，模型进行推理来生成回答，这个过程消耗 GPU 算力。",
    category: "基础概念",
  },
  {
    id: "parameters",
    term: "参数",
    termEn: "Parameters",
    definition: "模型在训练过程中学习到的数值权重，参数数量通常反映模型的规模和能力。",
    example: "GPT-3 有 1750 亿参数，Llama 3 有 700 亿参数版本，参数越多通常能力越强但成本越高。",
    category: "基础概念",
  },

  // ===== 技术术语 =====
  {
    id: "attention",
    term: "注意力机制",
    termEn: "Attention",
    definition: "让模型在处理某个位置时，能动态关注输入序列中其他相关位置信息的机制。",
    example: "翻译'The cat sat on the mat'时，翻译'cat'时模型会注意到'sat'来确定是主语。",
    category: "技术术语",
  },
  {
    id: "hallucination",
    term: "幻觉",
    termEn: "Hallucination",
    definition: "模型生成看似合理但实际上错误或虚构的内容，是当前 LLM 的主要问题之一。",
    example: "你问 AI 某篇论文的内容，它可能编造一个不存在的论文标题和作者，但说得头头是道。",
    category: "技术术语",
  },
  {
    id: "rag",
    term: "检索增强生成",
    termEn: "RAG (Retrieval-Augmented Generation)",
    definition: "先从外部知识库检索相关文档，再将检索结果作为上下文输入模型来生成答案的技术。",
    example: "企业客服 AI 先搜索产品文档找到相关段落，再基于这些段落回答用户问题，减少幻觉。",
    category: "技术术语",
  },
  {
    id: "vector-database",
    term: "向量数据库",
    termEn: "Vector Database",
    definition: "专门存储和检索高维向量的数据库，支持语义相似度搜索而非传统的关键词匹配。",
    example: "Pinecone、Weaviate 等向量数据库能快速找到与'如何养猫'语义相近的文档，即使文中没有'养猫'这个词。",
    category: "技术术语",
  },
  {
    id: "context-window",
    term: "上下文窗口",
    termEn: "Context Window",
    definition: "模型一次能处理的最大 token 数量，决定了模型能'看到'多少信息。",
    example: "Claude 3.5 有 200K token 上下文窗口，大约相当于一次能读 500 页文档。",
    category: "技术术语",
  },
  {
    id: "temperature",
    term: "温度参数",
    termEn: "Temperature",
    definition: "控制模型输出随机性的参数：温度越高输出越随机多样，温度越低输出越确定保守。",
    example: "写代码时设 temperature=0 让输出稳定可靠；写故事时设 temperature=0.8 让创意更丰富。",
    category: "技术术语",
  },
  {
    id: "top-p",
    term: "核采样",
    termEn: "Top-p (Nucleus Sampling)",
    definition: "生成时只考虑累积概率达到 p 的最高概率词汇集合，平衡多样性和质量。",
    example: "Top-p=0.9 意味着每次只从概率总和占 90% 的候选词中采样，过滤掉极低概率的奇怪输出。",
    category: "技术术语",
  },
  {
    id: "tokenizer",
    term: "分词器",
    termEn: "Tokenizer",
    definition: "将原始文本切分成模型可处理的 token 序列的工具，不同模型使用不同的分词策略。",
    example: "OpenAI 的 tiktoken 会把'unhappiness'拆成['un','happiness']，而中文通常按字或词组切分。",
    category: "技术术语",
  },
  {
    id: "gradient-descent",
    term: "梯度下降",
    termEn: "Gradient Descent",
    definition: "训练神经网络的核心优化算法，通过计算损失函数的梯度来更新参数，逐步减小预测误差。",
    example: "就像在山上蒙着眼找最低点，每一步都往脚下最陡的方向走，最终到达谷底。",
    category: "技术术语",
  },
  {
    id: "backpropagation",
    term: "反向传播",
    termEn: "Backpropagation",
    definition: "从输出层到输入层逐层计算误差梯度的算法，是神经网络学习的核心机制。",
    example: "模型预测错了，误差从最后一层往前传，告诉每一层的参数该怎么调整才能减小错误。",
    category: "技术术语",
  },

  // ===== 应用概念 =====
  {
    id: "agent",
    term: "智能体",
    termEn: "Agent",
    definition: "能自主感知环境、制定计划、调用工具并执行操作来完成目标的 AI 系统。",
    example: "Claude Code 是一个编程 Agent，你给它一个任务，它会自动分析代码、修改文件、运行测试。",
    category: "应用概念",
  },
  {
    id: "prompt-engineering",
    term: "提示工程",
    termEn: "Prompt Engineering",
    definition: "通过精心设计输入提示词来引导模型产生更好输出的技术和方法论。",
    example: "把'写一首诗'改为'请用五言绝句的格式，以春天为主题写一首诗'，输出质量会大幅提升。",
    category: "应用概念",
  },
  {
    id: "chain-of-thought",
    term: "思维链",
    termEn: "Chain-of-Thought (CoT)",
    definition: "让模型在给出最终答案前，先展示中间推理步骤的提示技术，能显著提升复杂推理能力。",
    example: "问'一个水池3小时放满，2小时抽干，同时开多久放满？'让模型写出每步计算过程再得答案。",
    category: "应用概念",
  },
  {
    id: "few-shot-learning",
    term: "少样本学习",
    termEn: "Few-shot Learning",
    definition: "在提示词中给模型少量示例，让它学会任务模式后处理新输入的技术。",
    example: "给模型3个情感分析示例(输入->正面/负面)，它就能对新评论做出正确分类。",
    category: "应用概念",
  },
  {
    id: "zero-shot",
    term: "零样本学习",
    termEn: "Zero-shot Learning",
    definition: "不给任何示例，仅通过指令描述就让模型完成从未见过的任务。",
    example: "直接说'把以下英文翻译成法语'，模型无需示例就能完成翻译任务。",
    category: "应用概念",
  },
  {
    id: "function-calling",
    term: "函数调用",
    termEn: "Function Calling",
    definition: "让模型能够识别何时需要调用外部函数，并生成符合规范的调用参数的能力。",
    example: "用户问'北京天气怎么样'，模型识别出需要调用天气 API，输出 {city:'北京'} 作为参数。",
    category: "应用概念",
  },
  {
    id: "multi-agent",
    term: "多智能体协作",
    termEn: "Multi-Agent",
    definition: "多个 AI Agent 分工协作完成复杂任务的架构，各 Agent 有专门的角色和能力。",
    example: "一个 Agent 负责写代码，一个负责审查，一个负责测试，协同完成软件开发任务。",
    category: "应用概念",
  },
  {
    id: "tool-use",
    term: "工具使用",
    termEn: "Tool Use",
    definition: "AI 模型能够调用外部工具(搜索、计算、API等)来弥补自身能力不足的技术。",
    example: "模型无法精确计算大数乘法，但可以调用计算器工具得到精确结果。",
    category: "应用概念",
  },
  {
    id: "guardrails",
    term: "护栏",
    termEn: "Guardrails",
    definition: "对 AI 输出设置的安全约束和限制机制，防止模型产生有害、违规或不当的内容。",
    example: "设置护栏让客服 AI 在不确定时说'我不确定，请联系人工客服'而不是编造答案。",
    category: "应用概念",
  },
  {
    id: "rlhf",
    term: "基于人类反馈的强化学习",
    termEn: "RLHF",
    definition: "通过人类对模型输出的偏好评分来训练奖励模型，再用强化学习优化 LLM 的技术。",
    example: "人工标注员对 AI 的多个回答排序好坏，模型学习人类偏好后变得更有帮助、更安全。",
    category: "应用概念",
  },

  // ===== 商业/生态 =====
  {
    id: "foundation-model",
    term: "基础模型",
    termEn: "Foundation Model",
    definition: "在大规模数据上预训练的通用模型，可以适配到各种下游任务，是 AI 应用的基石。",
    example: "GPT-4、Claude 3.5、Llama 3 都是基础模型，开发者基于它们构建各类 AI 应用。",
    category: "商业/生态",
  },
  {
    id: "open-source-model",
    term: "开源模型",
    termEn: "Open Source Model",
    definition: "公开模型权重和(部分)训练细节，允许社区免费使用和修改的模型。",
    example: "Meta 的 Llama 系列、Mistral 都是开源模型，任何人都可以下载部署到自己的服务器上。",
    category: "商业/生态",
  },
  {
    id: "api",
    term: "应用程序接口",
    termEn: "API (Application Programming Interface)",
    definition: "供开发者调用模型能力的编程接口，按调用量(通常是 token 数)计费。",
    example: "通过 OpenAI API 发送请求，每百万 token 约 $3-60 不等，取决于模型版本。",
    category: "商业/生态",
  },
  {
    id: "saas",
    term: "软件即服务",
    termEn: "SaaS (Software as a Service)",
    definition: "以云服务形式提供 AI 能力的商业模式，用户无需管理基础设施即可使用。",
    example: "ChatGPT Plus 月费 $20，用户直接通过网页使用，不需要自己买 GPU 部署模型。",
    category: "商业/生态",
  },
  {
    id: "gpu",
    term: "图形处理器",
    termEn: "GPU (Graphics Processing Unit)",
    definition: "AI 模型训练和推理的核心硬件，其并行计算能力特别适合深度学习的矩阵运算。",
    example: "NVIDIA H100 是目前最热门的 AI 训练 GPU，一张售价约 $30,000-40,000。",
    category: "商业/生态",
  },
  {
    id: "training-cost",
    term: "训练成本",
    termEn: "Training Cost",
    definition: "从零训练一个大模型所需的总花费，包括算力、数据、人力等各项成本。",
    example: "GPT-4 的训练成本据估计超过 1 亿美元，这还不包括前期的研究和数据准备费用。",
    category: "商业/生态",
  },
  {
    id: "scaling-law",
    term: "规模定律",
    termEn: "Scaling Law",
    definition: "描述模型性能如何随参数规模、数据量和计算量的增加而可预测地提升的经验法则。",
    example: "把模型参数增大10倍，在基准测试上的表现会有可预测的提升幅度。",
    category: "商业/生态",
  },
  {
    id: "benchmark",
    term: "基准测试",
    termEn: "Benchmark",
    definition: "用于标准化评估模型能力的测试集和评分体系，便于不同模型间横向对比。",
    example: "HumanEval 测试代码能力，MMLU 测试知识广度，各模型发布时都会公布这些分数。",
    category: "商业/生态",
  },
  {
    id: "mmlu",
    term: "大规模多任务语言理解",
    termEn: "MMLU",
    definition: "覆盖 57 个学科的选择题测试集，是衡量模型知识广度和推理能力的核心基准之一。",
    example: "GPT-4 在 MMLU 上达到 86.4% 准确率，接近人类专家水平的 89.8%。",
    category: "商业/生态",
  },
  {
    id: "alignment",
    term: "对齐",
    termEn: "Alignment",
    definition: "确保 AI 系统的行为符合人类意图和价值观的研究领域和技术实践。",
    example: "通过 RLHF、Constitutional AI 等技术让模型拒绝有害请求、遵循伦理准则。",
    category: "商业/生态",
  },
];
